### ISSUE TITLE
CSMA / CA

### ISSUE THREAD

**Issue by edgaralb** [newracom/nrc7292_sw_pkg#10]
Dear Newracom

Please I have some questions:
1. For media access (CSMA / CA), what is the name of the library to define the CCA threshold, variable name and threshold value.
2. How can I obtain the RSSI and SNR associated with the Rx package and what unit of measure is obtained.

In summary, I want to obtain the values of CCA threshold; 
And rssi and snr associated with the Rx packet. Because the rssi and snr values of the show signal and show stats simple rx commands do not vary, in the cases of different powers and with interferences. (Example: rssi = 5 and snr = 28, with various powers and interference, values that are maintained in all cases).

**Comment by newracom** [comment]
Dear customer,

Thank you for your inquiries. Please refer to the following answers.

1. Unfortunately, we do not provide any method to change the CCA level. Can I ask you what the purpose is to change the CCA level?
2. What kind of HW board are you using? Please let us know the model number and manufacturer. Instead of using the “show signal,” can you try again by using the “show signal <interval> <number of samples>” command? For example, you can give the command like “show signal 1 20” to see the RSSI/SNR 20 times with a 1-sec interval. Please refer to the attached console log, [show_signal_sample_log.txt](https://github.com/newracom/nrc7292_sw_pkg/files/6174380/show_signal_sample_log.txt)
